### ISSUE TITLE
Unable to build app after adding the buildpack

### ISSUE THREAD

**Issue by akxer** [fxtentacle/heroku-pdftk-buildpack#10]
I am receiving the following logs while building the heroku app, the stack is `cedar-14`
```
 !     error fetching custom buildpack https://elements.heroku.com/buildpacks/fxtentacle/heroku-pdftk-buildpack
 !     Push failed
```

Also tried using the github url, but then it says the app is not compatible

**Comment by fxtentacle** [comment]
Please contact Heroku support.
