### ISSUE TITLE
Add support for Heroku-20

### ISSUE THREAD

**Issue by edmorley** [fxtentacle/heroku-pdftk-buildpack#11]
Hi!

Heroku-20 beta was just released:
https://devcenter.heroku.com/changelog-items/1937

Trying this buildpack on a Heroku-20 app, the build currently fails with:

```
$ git init
$ h create --stack heroku-20 --buildpack https://github.com/fxtentacle/heroku-pdftk-buildpack
$ touch foo
$ git add -A && git commit -m '.' && git push heroku main
...
remote: -----> heroku-pdftk-buildpack app detected
remote: cp: cannot stat 'binaries-heroku-20/*': No such file or directory
remote:  !     Push rejected, failed to compile heroku-pdftk-buildpack app.
```

Would it be possible to:
1. Add the binaries directory for Heroku-20
2. Improve the error message shown when the binaries directory doesn't exist for the current stack?

Many thanks :-)

**Comment by zcericola** [comment]
Any idea what the ETA might be on this or a possible workaround in the meantime? I'm trying to go from Heroku 18 to 20 but am encountering this issue as well. Thanks!

**Comment by fxtentacle** [comment]
I have now uploaded my heroku-20 binaries.

But I would advise you to compile your own binaries from scratch anyway, purely for security reasons. I mean these binaries will likely execute on every server of your website deployment and nobody knows which issues lurk in the Ubuntu packages that I used for creating the binaries. 

The script to do the recompile is included in this repo.
