### ISSUE TITLE
support heroku-18 stack

### ISSUE THREAD

**Issue by kylekeesling** [fxtentacle/heroku-pdftk-buildpack#8]
Can you help me understand what it would take to add support for the new heroku-18 stack? I'm a newbie when it comes to making Heroku buildpacks, but if you point me in the right direction I'd be happy to help make it happen.

I forked and attempted it myself by just copying the `binaries-heroku-16`, to one named `binaries-heroku-18` but that didn't seem to do the trick.

https://github.com/kylekeesling/heroku-pdftk-buildpack

**Comment by fxtentacle** [comment]
I know that Heroku is listing my buildpack in their registry and they are presenting it more or less like this would be something official. But they are neither paying me, nor do I have any affiliation with them. I'm also not particularly happy about how Heroku has changed recently and the performance of my company's dynos keeps going down for no reason.

To make this work on Heroku 18, I believe you will need to re-compile the binaries, which probably requires patches, configuration set-up and/or source code changes. You'll have to ask the Heroku support about the details. But, ah, good luck with that. In my experience, the Heroku support was always apologizing, but never helpful.

Alternatively, you could try asking "eyefodder" here on GitHub. That's the person that submitted the heroku-16 binaries as a patch.

**Comment by kylekeesling** [comment]
Hi @eyefodder - do you have any tips on how to get this recompiled for Heroku-18?

**Comment by karladler** [comment]
@fxtentacle can you merge this PR? We tested it on Heroku 18, works perfect.

**Comment by jay-meister** [comment]
@fxtentacle this PR is good to go 👍

**Comment by sgeef** [comment]
@fxtentacle and ETA on when you can merge this in?

**Comment by lebrunthibault** [comment]
@fxtentacle Hello ! I would be interested in using this buildpack for heroku-18, is this pr still mergeable ?

Thanks !

**Comment by fxtentacle** [comment]
I now needed heroku-18 support myself, so I have updated the build script and uploaded the binaries that I compiled natively on a heroku-18 dyno.
